In [1]:
import numpy as np
import pandas as pd

In [2]:
#importing dataset
dataset = pd.read_csv("weatherAUS.csv")
X=dataset.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values
Y=dataset.iloc[:,-1].values


In [3]:
print(X)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 3.6 25.3 ... 10.9 24.5 'No']
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']]


In [4]:
print(Y)

['No' 'No' 'No' ... 'No' 'No' 'No']


In [5]:
Y=Y.reshape(-1,1)  #1d list into 2d list

In [6]:
print(Y)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]


In [7]:
#dealing with invalid dataset
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='most_frequent')
X=imputer.fit_transform(X)
Y=imputer.fit_transform(Y)

In [8]:
print(X)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 3.6 25.3 ... 10.9 24.5 'No']
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']]


In [9]:
print(Y)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]


In [10]:
#encoding dataset
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
X[:,0]=le1.fit_transform(X[:,0])
le2=LabelEncoder()
X[:,4]=le2.fit_transform(X[:,4])
le3=LabelEncoder()
X[:,6]=le3.fit_transform(X[:,6])
le4=LabelEncoder()
X[:,7]=le4.fit_transform(X[:,7])
le5=LabelEncoder()
X[:,-1]=le5.fit_transform(X[:,-1])
le6=LabelEncoder()
Y=le6.fit_transform(Y)





C:\Users\anuku\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [11]:
print(X)

[[2 13.4 22.9 ... 16.9 21.8 0]
 [2 7.4 25.1 ... 17.2 24.3 0]
 [2 12.9 25.7 ... 21.0 23.2 0]
 ...
 [41 3.6 25.3 ... 10.9 24.5 0]
 [41 5.4 26.9 ... 12.5 26.1 0]
 [41 7.8 27.0 ... 15.1 26.0 0]]


In [12]:
print(Y)

[0 0 0 ... 0 0 0]


In [13]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)



In [14]:
print(X) #DATA IS IN THE RANGE TO PLOT ON GRAPH

[[-1.5270045   0.19169797 -0.044926   ... -0.01353307  0.02110819
  -0.53296232]
 [-1.5270045  -0.74708764  0.26444584 ...  0.03281942  0.38476354
  -0.53296232]
 [-1.5270045   0.11346584  0.34881998 ...  0.61995105  0.22475519
  -0.53296232]
 ...
 [ 1.21224943 -1.34165186  0.29257055 ... -0.94058301  0.41385597
  -0.53296232]
 [ 1.21224943 -1.06001618  0.51756825 ... -0.69336969  0.64659539
  -0.53296232]
 [ 1.21224943 -0.68450193  0.53163061 ... -0.29164805  0.63204918
  -0.53296232]]


In [15]:
##Splitting dataset into training set and test set
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)




In [16]:
print(X_train)

[[ 1.56343583  0.26993011 -0.08711307 ...  0.28003274 -0.18253881
  -0.53296232]
 [-1.10558082  1.59987639  0.86912716 ...  1.45429598  0.85024239
   1.87630525]
 [-1.45676722 -0.38721982  1.82536739 ...  1.77876346  1.94120845
  -0.53296232]
 ...
 [-1.66747906 -0.04299843 -0.79023088 ... -0.38435305 -0.66256387
   1.87630525]
 [ 0.50987663 -0.70014836  0.39100704 ... -0.39980388  0.42840218
  -0.53296232]
 [ 1.63367311  1.22436215  1.16443664 ...  1.40794349  0.16657033
  -0.53296232]]


In [17]:
print(Y_train)

[0 0 0 ... 0 0 1]


In [18]:
#training model
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=150,random_state=0)
classifier.fit(X_train,Y_train)



RandomForestClassifier(n_estimators=150, random_state=0)

In [19]:
classifier.score(X_train,Y_train)

0.9999296728027146

In [20]:
print(Y_test)

[0 0 0 ... 0 0 1]


In [21]:
Y_test=Y_test.reshape(-1,1)
print(Y_test)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [1]]


In [22]:
y_pred=classifier.predict(X_test)

In [23]:
print(y_pred)

[0 0 0 ... 0 0 1]


In [24]:
y_pred = le6.inverse_transform(y_pred)

In [25]:
print(y_pred)

['No' 'No' 'No' ... 'No' 'No' 'Yes']


In [26]:
print(Y_test)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [1]]


In [27]:
Y_test=le6.inverse_transform(Y_test)

C:\Users\anuku\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:153: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [28]:
print(Y_test)

['No' 'No' 'No' ... 'No' 'No' 'Yes']


In [29]:
Y_test=Y_test.reshape(-1,1)
y_pred=y_pred.reshape(-1,1)

In [30]:
df=np.concatenate((Y_test,y_pred),axis=1)
dataframe=pd.DataFrame(df,columns=["Rain on Tommorrow","Prediction of Rain"])


In [31]:
print(df)

[['No' 'No']
 ['No' 'No']
 ['No' 'No']
 ...
 ['No' 'No']
 ['No' 'No']
 ['Yes' 'Yes']]


In [32]:
print(dataframe)

      Rain on Tommorrow Prediction of Rain
0                    No                 No
1                    No                 No
2                    No                 No
3                    No                 No
4                    No                 No
...                 ...                ...
28434                No                 No
28435                No                 No
28436                No                 No
28437                No                 No
28438               Yes                Yes

[28439 rows x 2 columns]


In [33]:
#calculating accuracy
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)


0.8564998769295685

In [34]:
dataframe.to_csv('prediction.csv')
print('Predictions saved to prediction.csv')

Predictions saved to prediction.csv
